[package]
name = "anypctoolbox"
version = "1.0.0"
description = "AnyPCToolbox - 跨平台实用工具箱桌面应用"
authors = ["AnyPCToolbox"]
edition = "2021"

[lib]
name = "anypctoolbox_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true